/*
    IN THIS FILE, THERE WILL BE FEATURES FOR SIMULATING PURCHASES, TRANSACTIONS AND OTHER INTERACTIONS WITH THE PROGRAM THAT AREN'T A DIRECT PART OF THE BANKING SYSTEM.
*/

#ifndef SIMULATION_H
#define SIMULATION_H
#endif // SIMULATION_H